#include <mpi.h>
#include <iostream>
#include <cstdlib>
#include <ctime>

int main(int argc, char* argv[]) {
    MPI_Init(&argc, &argv);

    int rank, size;
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    MPI_Comm_size(MPI_COMM_WORLD, &size);

    const int n = 100;
    int* x_global = new int[n];

    // Шаг 1: Процесс 0 генерирует массив [0..9]
    if (rank == 0) {
        std::srand(static_cast<unsigned int>(std::time(nullptr)));
        for (int i = 0; i < n; ++i) {
            x_global[i] = std::rand() % 10;
        }
        std::cout << "Global array (generated by rank 0):\n";
        for (int i = 0; i < n; ++i) {
            std::cout << x_global[i] << " ";
        }
        std::cout << std::endl;
    }

    // Шаг 2: Полная кольцевая передача (двухточечный обмен)
    // Кольцо: 0 → 1 → 2 → ... → (size-1) → 0
    if (size > 1) {
        int prev = (rank - 1 + size) % size;
        int next = (rank + 1) % size;

        if (rank == 0) {
            MPI_Send(x_global, n, MPI_INT, next, 0, MPI_COMM_WORLD);
            MPI_Recv(x_global, n, MPI_INT, prev, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
        } else {
            MPI_Recv(x_global, n, MPI_INT, prev, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
            MPI_Send(x_global, n, MPI_INT, next, 0, MPI_COMM_WORLD);
        }
    }

    //  Шаг 3: Подсчёт чётных на индексах, кратных номеру процесса
    int local_even = 0;
    if (rank == 0) {
        for (int i = 0; i < n; ++i) {
            if (x_global[i] % 2 == 0) ++local_even;
        }
    } else {
        for (int i = 0; i < n; ++i) {
            if (i % rank == 0 && x_global[i] % 2 == 0) ++local_even;
        }
    }

    //  Шаг 4: Сбор результатов на процессе 0
    if (rank == 0) {
        int* even_number = new int[size];
        even_number[0] = local_even;

        for (int i = 1; i < size; ++i) {
            MPI_Recv(&even_number[i], 1, MPI_INT, i, 1,
                     MPI_COMM_WORLD, MPI_STATUS_IGNORE);
        }

        std::cout << "\nCount of even numbers for every rank:\n";
        for (int i = 0; i < size; ++i) {
            std::cout << "rank: " << i << ", count: " << even_number[i] << std::endl;
        }

        delete[] even_number;
    } else {
        MPI_Send(&local_even, 1, MPI_INT, 0, 1, MPI_COMM_WORLD);
    }

    delete[] x_global;
    MPI_Finalize();
    return 0;
}
